# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       database:
           entity:
               class: App:User
               property: idpId

       cron:
         memory:
           users:
             cron:
               password: '%env(CRON_PASSWORD)%'
               roles: [ 'ROLE_CRON' ]

       status_link:
          id: App\Security\Authentication\Provider\StatusLinkTokenProvider

       calendar:
          id: App\Security\Authentication\Provider\CalendarTokenProvider

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      AppBundle\Entity\User: bcrypt

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
      ROLE_GROUP_CREATOR: [ 'ROLE_USER' ]
      ROLE_ADMIN: [ 'ROLE_GROUP_CREATOR' ]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        cron:
            pattern: ^/cron
            http_basic:
              realm: 'Cronjob'
              provider: cron
            stateless: true

        login:
            anonymous: ~
            pattern: ^/saml/(login|discovery)$

        logout:
            anonymous: ~
            pattern: ^/logout/success

        status_change:
            pattern: ^/mail/change_status
            stateless: true
            status_link_token: true
            provider: status_link

        ics:
            pattern: ^/ics
            stateless: true
            calendar_token: true
            provider: calendar

        secured:
            pattern: ^/
            light_saml_sp:
                provider: database
                user_creator: App\Security\User\UserCreator
                login_path: /saml/login
                check_path: /saml/login_check
                attribute_mapper: App\Security\User\AttributeMapper
                token_factory: SchulIT\CommonBundle\Security\Factory\SamlSpTokenFactory
                failure_path: /auth/error
            logout:
                path: /logout
                target: /logout/success

        main:
            anonymous: ~