twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - "@Common/form.html.twig"
    globals:
      config: '@app.common.config'
      user: '@App\Twig\UserVariable'
      profile_url: "%env(IDP_PROFILE_URL)%"